language: node_js
node_js:
  - 8
cache:
  directories:
    - ~/.npm
    - ~/.cache
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
install:
  - npm install
script:
  - npm run lint
  - npm run build
  - npm run test
after_success:
  - npm run semantic-release
